server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend-service:5000/;
    }

    location /health {
        proxy_pass http://backend-service:5000/health;
    }

    location /deployments/ {
        proxy_pass http://backend-service:5000/deployments/;
    }

    location /auth/ {
        proxy_pass http://backend-service:5000/auth/;
    }

    location /github/ {
        proxy_pass http://backend-service:5000/github/;
    }
}