server {
    listen 80;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://backend-service:5000/;
    }

    location /health {
        proxy_pass http://backend-service:5000/health;
    }

    location /deployments/ {
        proxy_pass http://backend-service:5000/deployments/;
    }

    location /auth/ {
        proxy_pass http://backend-service:5000/auth/;
    }

    location /github/ {
        proxy_pass http://backend-service:5000/github/;
    }
    location /metrics {
        proxy_pass http://backend-service:5000/metrics;
    }
    location /servers {
        proxy_pass http://backend-service:5000/servers;
    }
    location /jobs {
        proxy_pass http://backend-service:5000/jobs;
    }
    location /ws/ {
        proxy_pass http://backend-service:5000/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
# server {
#     listen 80;

#     server_name localhost;

#     root /usr/share/nginx/html;
#     index index.html;

#     location / {
#         try_files $uri $uri/ /index.html;
#     }

#     location /api/ {
#         proxy_pass http://localhost:5000/;
#     }

#     location /health {
#         proxy_pass http://localhost:5000/health;
#     }

#     location /deployments/ {
#         proxy_pass http://localhost:5000/deployments/;
#     }

#     location /auth/ {
#         proxy_pass http://localhost:5000/auth/;
#     }

#     location /github/ {
#         proxy_pass http://localhost:5000/github/;
#     }
#     location /metrics {
#         proxy_pass http://localhost:5000/metrics;
#     }
#     location /servers {
#         proxy_pass http://localhost:5000/servers;
#     }
#     location /jobs {
#         proxy_pass http://localhost:5000/jobs;
#     }
# }